const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {createRequire}=require('node:module');
const model=require('../miniprogram/utils/model');
const pageFile=path.resolve(__dirname,'../miniprogram/pages/index/index.js');
function loadPage(){let page;const wx={showToast(){},pageScrollTo(){},showModal(){},getStorageSync(){},setStorageSync(){},getWindowInfo(){return{statusBarHeight:24};}};vm.runInNewContext(fs.readFileSync(pageFile,'utf8'),{require:createRequire(pageFile),Page:p=>{page=p;},wx,console,Set,Math,Date,Promise,setTimeout,clearTimeout});page.data=JSON.parse(JSON.stringify(page.data));page.setData=function(patch){for(const[k,v]of Object.entries(patch)){const parts=k.replace(/\[(\d+)\]/g,'.$1').split('.');let target=this.data;for(const key of parts.slice(0,-1))target=target[key];target[parts.at(-1)]=v;}};page._failedImages=new Set();page._session={id:'fixture',person:'a'};page._busy=new Set();return page;}
function fixture(){return{id:'fixture',version:1,mode:'together',decisionMode:'random',turn:'a',people:{a:'小鹿',b:'小熊'},dishes:structuredClone(model.dishes),votes:{a:{},b:{}},favorites:{a:[],b:[]},history:[],online:{a:true,b:false},proposal:null};}
test('原生页面派生正确的身份、匹配和筛选视图',()=>{const page=loadPage();const room=fixture();room.votes.a.d2='yes';room.votes.b.d2='yes';page.applyRoom(room);assert.equal(page.data.loading,false);assert.equal(page.data.matched.length,1);assert.equal(page.data.dishes.find(d=>d.id==='d2').matched,true);page.switchPerson({currentTarget:{dataset:{person:'b'}}});assert.equal(page.data.person,'b');assert.equal(page.data.ownName,'小熊');page.search({detail:{value:'南瓜'}});assert.equal(page.data.dishes.length,1);assert.equal(page.data.dishes[0].id,'d7');});
test('原生远程身份不可切换；过期状态与其他房间状态被忽略',()=>{const page=loadPage();const room=fixture();room.mode='remote';page.applyRoom(room);page.switchPerson({currentTarget:{dataset:{person:'b'}}});assert.equal(page.data.person,'a');page.applyRoom({...room,version:0});assert.equal(page.data.room.version,1);page.applyRoom({...room,id:'another-room',version:10});assert.equal(page.data.room.id,'fixture');});
test('原生推荐状态撤回时关闭弹层，损坏图片降级',()=>{const page=loadPage();const room=fixture();room.proposal={id:'proposal',dish:room.dishes[0]};page.applyRoom(room);page.setData({modal:'draw'});assert.equal(page.data.pending.spiceLabel,'不辣');page.applyRoom({...room,version:2,proposal:null});assert.equal(page.data.modal,'');page.imageError({currentTarget:{dataset:{id:'d1'}}});assert.equal(page.data.dishes.find(d=>d.id==='d1').image,'');});
test('原生 WXML 的事件绑定均有页面方法实现',()=>{const page=loadPage();const markup=fs.readFileSync(path.join(path.dirname(pageFile),'index.wxml'),'utf8');const handlers=[...markup.matchAll(/(?:bind|catch)(?:tap|input|change|error)="([^"]+)"/g)].map(m=>m[1]);assert.ok(handlers.length>30);for(const name of new Set(handlers))assert.equal(typeof page[name],'function',`缺少事件处理 ${name}`);});
test('原生模板的条件与循环使用数据绑定而非字面字符串',()=>{const markup=fs.readFileSync(path.join(path.dirname(pageFile),'index.wxml'),'utf8');for(const match of markup.matchAll(/wx:(if|elif|for)="([^"]+)"/g)){assert.match(match[2],/^\{\{.+\}\}$/s,`无效的 ${match[1]} 表达式: ${match[2]}`);}});
test('原生私房菜编辑器正确恢复分类索引与内容',()=>{const page=loadPage();const room=fixture();room.dishes.push({...room.dishes[0],id:'custom',custom:true,kind:'素菜',category:'暖心汤羹'});page.applyRoom(room);page.edit({currentTarget:{dataset:{id:'custom'}}});assert.equal(page.data.modal,'dish');assert.equal(page.data.formKindIndex,1);assert.equal(page.data.formCategoryIndex,3);page.formSelect({currentTarget:{dataset:{field:'kind'}},detail:{value:'0'}});assert.equal(page.data.form.kind,'荤菜');page.close();assert.equal(page.data.modal,'');});
